package com.optogo.utils.enums;

public enum SymptomName {
    DIMINISHED_VISION,
    SYMPTOMS_OF_EYE,
    LACRIMATION,
    SPOTS_OR_CLOUDS_IN_VISION,
    EYE_REDNESS,
    EYE_MOVES_ABNORMALLY,
    BLINDNESS,
    ITCHINESS_OF_EYE,
    FOREIGN_BODY_SENSATION_IN_EYE,
    EYE_DEVIATION,
    CROSS_EYED,
    DOUBLE_VISION,
    ABNORMAL_MOVEMENT_OF_EYELID,
    PAIN_IN_EYE,
    EYE_BURNS_OR_STINGS,
    SWOLLEN_EYE,
    EYELID_SWELLING,
    EYELID_LESION_OR_RASH
}
